#!/usr/bin/env node
// Resolve the current published `stormlog` version at build time so the
// landing site never drifts from what teams actually install.
//
// Primary source : PyPI (https://pypi.org/project/stormlog/) — what `pip install` gets.
// Fallback source: the stormlog GitHub tag list.
// Offline safety : if neither is reachable, the previously generated value is
//                  kept (and only a baked-in default is written when no file exists).
//
// This script is intentionally side-effect-safe: it never throws and never exits
// non-zero, so a flaky network can never break a deploy. It only touches the
// landing repo's generated constant — never the stormlog project.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.join(ROOT, "..", "src", "data", "stormlog-version.ts");
const DEFAULT_VERSION = "0.3.6";

const PYPI_URL = "https://pypi.org/pypi/stormlog/json";
const GITHUB_TAGS_URL =
  "https://api.github.com/repos/Silas-Asamoah/stormlog/tags";

// Accepts 1.2.3 and common suffixes (1.2.3rc1, 1.2.3.post1, 1.2.3-beta.1, …).
const SEMVER_LIKE = /^\d+\.\d+\.\d+([.\-+][0-9A-Za-z.\-+]*)?$/;

async function fetchJson(url) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10_000);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: {
        Accept: "application/json",
        "User-Agent": "stormlog-landing-version-sync",
      },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timeout);
  }
}

function normalize(value) {
  if (typeof value !== "string") return null;
  const cleaned = value.trim().replace(/^v/, "");
  return SEMVER_LIKE.test(cleaned) ? cleaned : null;
}

async function fromPyPI() {
  try {
    const data = await fetchJson(PYPI_URL);
    return normalize(data?.info?.version);
  } catch {
    return null;
  }
}

async function fromGitHubTags() {
  try {
    const tags = await fetchJson(GITHUB_TAGS_URL);
    if (!Array.isArray(tags)) return null;
    for (const tag of tags) {
      const normalized = normalize(tag?.name);
      if (normalized) return normalized;
    }
    return null;
  } catch {
    return null;
  }
}

async function readCurrent() {
  try {
    const source = await readFile(OUT_FILE, "utf8");
    const match = source.match(/STORMLOG_VERSION\s*=\s*"([^"]+)"/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function render(version) {
  return `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Source of truth: the latest published \`stormlog\` release on PyPI
// (https://pypi.org/project/stormlog/), with the GitHub tag list as a fallback.
// Regenerate with: npm run sync-version
export const STORMLOG_VERSION = "${version}";
`;
}

async function main() {
  const current = await readCurrent();
  const resolved = (await fromPyPI()) ?? (await fromGitHubTags());

  if (!resolved) {
    if (current === null) {
      await writeFile(OUT_FILE, render(DEFAULT_VERSION));
      console.warn(
        `[sync-version] no source reachable; wrote default v${DEFAULT_VERSION}`
      );
    } else {
      console.warn(
        `[sync-version] PyPI/GitHub unreachable; keeping existing v${current}`
      );
    }
    return;
  }

  if (resolved === current) {
    console.log(`[sync-version] up to date (v${resolved})`);
    return;
  }

  await writeFile(OUT_FILE, render(resolved));
  console.log(`[sync-version] updated v${current ?? "none"} -> v${resolved}`);
}

main().catch((error) => {
  // Never fail the build over a version refresh.
  console.warn(`[sync-version] skipped: ${error?.message ?? error}`);
});
